server:
  port: 10086


spring:
  application:
    name: eureka_server
eureka:
  client:
    allow-redirects: false
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    fetch-registry: false
  server:
    eviction-interval-timer-in-ms: 60000
    enable-self-preservation: false
